// Drum patterns adapted from René-Pierre Bardet, "200/260 Drum Machine Patterns"
// (via github.com/stephenhandley/DrumMachinePatterns transcriptions). Rhythm
// patterns are not copyrightable; accents map to velocity.

export interface DrumLanePattern {
  /** 32 steps (2 bars of 16ths); 0 = rest, >0 = velocity */
  steps: number[]
}

export interface NoteEvent {
  /** Position in beats, 0-indexed, 0..7.75 (2 bars in 4/4) */
  time: number
  /** Note name, e.g. 'E2' — passed to createOscillator({ note }) */
  note: string
}

export interface ChordEvent {
  time: number
  notes: string[]
  /** Grid display label, e.g. 'Em' */
  label: string
}

export interface VoiceSpec {
  type: OscillatorType // 'sine' | 'square' | 'sawtooth' | 'triangle'
  gain: number
  envelope: { attack: number, decay: number, sustain: number, release: number }
}

export interface TransportPreset {
  name: string
  bpm: number
  /** 0–1, applied to transport.swing on preset select */
  swing: number
  kick: DrumLanePattern
  snare: DrumLanePattern
  hihat: DrumLanePattern
  bass: { voice: VoiceSpec, notes: NoteEvent[] }
  lead: { voice: VoiceSpec, notes: ChordEvent[] }
}

export const ACCENT = 1
export const NORMAL = 0.7
export const GHOST = 0.4

const rock: TransportPreset = {
  name: 'Rock',
  bpm: 112,
  swing: 0,
  kick: {
    steps: [
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
    ],
  },
  snare: {
    steps: [
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
    ],
  },
  hihat: {
    steps: [
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      NORMAL,
      0,
    ],
  },
  bass: {
    voice: {
      type: 'triangle',
      gain: 0.5,
      envelope: { attack: 0.005, decay: 0.25, sustain: 0, release: 0.05 },
    },
    notes: [
      { time: 0, note: 'E2' },
      { time: 1.5, note: 'E2' },
      { time: 2, note: 'G2' },
      { time: 3, note: 'A2' },
      { time: 4, note: 'E2' },
      { time: 5.5, note: 'E2' },
      { time: 6, note: 'G2' },
      { time: 7, note: 'D2' },
    ],
  },
  lead: {
    voice: {
      type: 'sawtooth',
      gain: 0.22,
      envelope: { attack: 0.005, decay: 0.3, sustain: 0, release: 0.08 },
    },
    notes: [
      { time: 1.5, notes: ['E4', 'G4', 'B4'], label: 'Em' },
      { time: 3.5, notes: ['E4', 'G4', 'B4'], label: 'Em' },
      { time: 5.5, notes: ['E4', 'G4', 'B4'], label: 'Em' },
      { time: 7.5, notes: ['G4', 'B4', 'D5'], label: 'G' },
    ],
  },
}

const funk: TransportPreset = {
  name: 'Funk',
  bpm: 104,
  swing: 0.15,
  kick: {
    steps: [
      ACCENT,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
    ],
  },
  snare: {
    steps: [
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      GHOST,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      GHOST,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      GHOST,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
    ],
  },
  hihat: {
    steps: [
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
      ACCENT,
      GHOST,
      NORMAL,
      GHOST,
    ],
  },
  bass: {
    voice: {
      type: 'square',
      gain: 0.4,
      envelope: { attack: 0.005, decay: 0.18, sustain: 0, release: 0.04 },
    },
    notes: [
      { time: 0, note: 'A1' },
      { time: 0.75, note: 'A1' },
      { time: 1.25, note: 'A2' },
      { time: 2.5, note: 'G1' },
      { time: 3, note: 'A1' },
      { time: 4, note: 'A1' },
      { time: 4.75, note: 'C2' },
      { time: 5, note: 'D2' },
      { time: 5.75, note: 'E2' },
      { time: 6.5, note: 'G1' },
      { time: 7, note: 'A1' },
    ],
  },
  lead: {
    voice: {
      type: 'square',
      gain: 0.16,
      envelope: { attack: 0.003, decay: 0.15, sustain: 0, release: 0.05 },
    },
    notes: [
      { time: 1.5, notes: ['A3', 'C4', 'E4', 'G4'], label: 'Am7' },
      { time: 3.75, notes: ['A3', 'C4', 'E4', 'G4'], label: 'Am7' },
      { time: 5.5, notes: ['A3', 'C4', 'E4', 'G4'], label: 'Am7' },
      { time: 7.5, notes: ['A3', 'C4', 'E4', 'G4'], label: 'Am7' },
    ],
  },
}

const disco: TransportPreset = {
  name: 'Disco',
  bpm: 118,
  swing: 0,
  kick: {
    steps: [
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
    ],
  },
  snare: {
    steps: [
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
    ],
  },
  hihat: {
    steps: [
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
      GHOST,
      0,
      ACCENT,
      0,
    ],
  },
  bass: {
    voice: {
      type: 'sawtooth',
      gain: 0.35,
      envelope: { attack: 0.005, decay: 0.2, sustain: 0, release: 0.05 },
    },
    notes: [
      { time: 0, note: 'A1' },
      { time: 0.5, note: 'A2' },
      { time: 1, note: 'A1' },
      { time: 1.5, note: 'A2' },
      { time: 2, note: 'A1' },
      { time: 2.5, note: 'A2' },
      { time: 3, note: 'A1' },
      { time: 3.5, note: 'A2' },
      { time: 4, note: 'A1' },
      { time: 4.5, note: 'A2' },
      { time: 5, note: 'A1' },
      { time: 5.5, note: 'A2' },
      { time: 6, note: 'A1' },
      { time: 6.5, note: 'A2' },
      { time: 7, note: 'G1' },
      { time: 7.5, note: 'G2' },
    ],
  },
  lead: {
    voice: {
      type: 'sawtooth',
      gain: 0.14,
      envelope: { attack: 0.005, decay: 0.22, sustain: 0, release: 0.06 },
    },
    notes: [
      { time: 1, notes: ['A4', 'E5'], label: 'Am' },
      { time: 3, notes: ['A4', 'E5'], label: 'Am' },
      { time: 5, notes: ['A4', 'E5'], label: 'Am' },
      { time: 7, notes: ['G4', 'D5'], label: 'G' },
    ],
  },
}

const bossa: TransportPreset = {
  name: 'Bossa',
  bpm: 132,
  swing: 0,
  kick: {
    steps: [
      ACCENT,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      0,
      NORMAL,
      0,
      0,
      0,
      0,
    ],
  },
  snare: {
    steps: [
      0.5,
      0,
      0,
      0,
      0,
      0,
      0.5,
      0,
      0,
      0,
      0,
      0,
      0.5,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0.5,
      0,
      0,
      0,
      0,
      0,
      0.5,
      0,
      0,
      0,
      0,
      0,
    ],
  },
  hihat: {
    steps: [
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
      0.9,
      0,
      0.6,
      0,
    ],
  },
  bass: {
    voice: {
      type: 'triangle',
      gain: 0.45,
      envelope: { attack: 0.008, decay: 0.3, sustain: 0, release: 0.06 },
    },
    notes: [
      { time: 0, note: 'C2' },
      { time: 1.5, note: 'G1' },
      { time: 2, note: 'C2' },
      { time: 3.5, note: 'G1' },
      { time: 4, note: 'A1' },
      { time: 5.5, note: 'E1' },
      { time: 6, note: 'A1' },
      { time: 7.5, note: 'G1' },
    ],
  },
  lead: {
    voice: {
      type: 'sine',
      gain: 0.2,
      envelope: { attack: 0.01, decay: 0.35, sustain: 0, release: 0.1 },
    },
    notes: [
      { time: 1.5, notes: ['C4', 'E4', 'G4', 'B4'], label: 'Cmaj7' },
      { time: 3.5, notes: ['C4', 'E4', 'G4', 'B4'], label: 'Cmaj7' },
      { time: 5.5, notes: ['A3', 'C4', 'E4', 'G4'], label: 'Am7' },
      { time: 7.5, notes: ['A3', 'C4', 'E4', 'G4'], label: 'Am7' },
    ],
  },
}

const shuffle: TransportPreset = {
  name: 'Shuffle',
  bpm: 96,
  swing: 0.55,
  kick: {
    steps: [
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      NORMAL,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
    ],
  },
  snare: {
    steps: [
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      ACCENT,
      0,
      0,
      0,
    ],
  },
  hihat: {
    steps: [
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
      ACCENT,
      0,
      0.6,
      0,
    ],
  },
  bass: {
    voice: {
      type: 'triangle',
      gain: 0.5,
      envelope: { attack: 0.005, decay: 0.28, sustain: 0, release: 0.05 },
    },
    notes: [
      { time: 0, note: 'E2' },
      { time: 0.5, note: 'G2' },
      { time: 1, note: 'A2' },
      { time: 2, note: 'B2' },
      { time: 2.5, note: 'A2' },
      { time: 3, note: 'G2' },
      { time: 4, note: 'E2' },
      { time: 4.5, note: 'G2' },
      { time: 5, note: 'A2' },
      { time: 6, note: 'B2' },
      { time: 6.5, note: 'D3' },
      { time: 7, note: 'B2' },
    ],
  },
  lead: {
    voice: {
      type: 'triangle',
      gain: 0.2,
      envelope: { attack: 0.005, decay: 0.25, sustain: 0, release: 0.08 },
    },
    notes: [
      { time: 1.5, notes: ['E4', 'G#4', 'D5'], label: 'E7' },
      { time: 3.5, notes: ['E4', 'G#4', 'D5'], label: 'E7' },
      { time: 5.5, notes: ['E4', 'G#4', 'D5'], label: 'E7' },
      { time: 7.5, notes: ['A4', 'C#5', 'E5'], label: 'A' },
    ],
  },
}

export const TRANSPORT_PRESETS: TransportPreset[] = [rock, funk, disco, bossa, shuffle]
