import type { HeadConfig } from 'vitepress'
import { defineConfig } from 'vitepress'
import llmstxt from 'vitepress-plugin-llms'

// Import TypeDoc-generated sidebar (will exist after typedoc runs)
// Using dynamic import to avoid TS errors if file doesn't exist yet
let typedocSidebar: any[] = []
try {
  typedocSidebar = await import('../api/typedoc-sidebar.json')
  // Handle both default export and direct array
  if (typedocSidebar && 'default' in typedocSidebar) {
    typedocSidebar = (typedocSidebar as any).default
  }
}
catch {
  // Will be generated by typedoc
}

export default defineConfig({
  title: 'EZ Web Audio',
  description: 'A zero-dependency TypeScript library that makes the Web Audio API easy — play sounds, synthesizers, drum machines, and audio effects with minimal code.',
  base: '/ez-web-audio/',

  sitemap: {
    hostname: 'https://sethbrasile.github.io/ez-web-audio',
  },

  head: [
    // Favicon
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/ez-web-audio/favicon.svg' }],

    // Basic meta tags
    ['meta', { name: 'keywords', content: 'web audio api, javascript audio library, typescript audio, synthesizer, oscillator, drum machine, audio effects, sound playback, browser audio, audio visualization' }],
    ['meta', { name: 'author', content: 'Seth Brasile' }],
    ['meta', { name: 'robots', content: 'index, follow' }],

    // OpenGraph tags
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'EZ Web Audio' }],
    ['meta', { property: 'og:image', content: 'https://sethbrasile.github.io/ez-web-audio/og-image.png' }],
    ['meta', { property: 'og:image:width', content: '1200' }],
    ['meta', { property: 'og:image:height', content: '630' }],
    ['meta', { property: 'og:image:alt', content: 'EZ Web Audio - Simple Web Audio API for TypeScript' }],

    // Twitter Card tags
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: 'https://sethbrasile.github.io/ez-web-audio/og-image.png' }],

    // JSON-LD structured data
    ['script', { type: 'application/ld+json' }, JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareSourceCode',
      'name': 'ez-web-audio',
      'description': 'Zero-dependency TypeScript library that wraps the Web Audio API with a simpler, more intuitive interface.',
      'url': 'https://github.com/sethbrasile/ez-web-audio',
      'codeRepository': 'https://github.com/sethbrasile/ez-web-audio',
      'programmingLanguage': ['TypeScript', 'JavaScript'],
      'runtimePlatform': 'Browser',
      'license': 'https://opensource.org/licenses/MIT',
      'author': {
        '@type': 'Person',
        'name': 'Seth Brasile',
        'url': 'https://github.com/sethbrasile',
      },
      'version': '1.0.0',
      'dateCreated': '2026-01-31',
    })],
  ],

  transformHead(context) {
    const head: HeadConfig[] = []
    const canonicalUrl = `https://sethbrasile.github.io/ez-web-audio/${context.pageData.relativePath.replace(/index\.md$/, '').replace(/\.md$/, '')}`

    // Canonical URL
    head.push(['link', { rel: 'canonical', href: canonicalUrl }])

    // Per-page OG tags (override static defaults)
    const title = context.pageData.frontmatter.title || context.pageData.title
    const description = context.pageData.frontmatter.description || context.pageData.description

    if (title) {
      head.push(['meta', { property: 'og:title', content: `${title} | EZ Web Audio` }])
      head.push(['meta', { name: 'twitter:title', content: `${title} | EZ Web Audio` }])
    }
    if (description) {
      head.push(['meta', { property: 'og:description', content: description }])
      head.push(['meta', { name: 'twitter:description', content: description }])
    }

    // Per-page canonical in OG
    head.push(['meta', { property: 'og:url', content: canonicalUrl }])

    return head
  },

  vite: {
    plugins: [llmstxt({ domain: 'https://sethbrasile.github.io' })],
  },

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Examples', link: '/examples/' },
      { text: 'API', link: '/api/' },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
            { text: 'Core Concepts', link: '/guide/concepts' },
            { text: 'Parameter Control', link: '/guide/parameter-control' },
            { text: 'Utilities', link: '/guide/utilities' },
          ],
        },
        {
          text: 'Advanced',
          items: [
            { text: 'Multiple AudioContexts', link: '/guide/multiple-contexts' },
          ],
        },
      ],
      '/examples/': [
        {
          text: 'Examples',
          items: [
            { text: 'Overview', link: '/examples/' },
            { text: 'Basic Playback', link: '/examples/basic-playback' },
          ],
        },
        {
          text: 'Sampling',
          items: [
            { text: 'Sampled Drum Kit', link: '/examples/sampled-drum-kit' },
            { text: 'Soundfont Piano', link: '/examples/soundfont-piano' },
          ],
        },
        {
          text: 'Synthesis',
          items: [
            { text: 'Synthesis', link: '/examples/synthesis' },
            { text: 'Synth Keyboard', link: '/examples/synth-keyboard' },
            { text: 'XY Pad', link: '/examples/xy-pad' },
            { text: 'Synth Drum Kit', link: '/examples/synth-drum-kit' },
          ],
        },
        {
          text: 'Timing & Sequencing',
          items: [
            { text: 'Timing Basics', link: '/examples/timing' },
            { text: 'Drum Machine', link: '/examples/drum-machine' },
          ],
        },
        {
          text: 'Integration Patterns',
          items: [
            { text: 'Vue Reactive Pattern', link: '/examples/drum-machine-vue' },
            { text: 'Vanilla TS Events', link: '/examples/drum-machine-vanilla' },
            { text: 'React Integration', link: '/examples/react-integration' },
          ],
        },
        {
          text: 'Effects & Routing',
          items: [
            { text: 'Effects', link: '/examples/effects' },
            { text: 'Audio Routing', link: '/examples/audio-routing' },
          ],
        },
        {
          text: 'Composition',
          items: [
            { text: 'Audio Sprite', link: '/examples/audio-sprite' },
            { text: 'Layered Sound', link: '/examples/layered-sound' },
            { text: 'Crossfade', link: '/examples/crossfade' },
          ],
        },
        {
          text: 'Creative',
          items: [
            { text: 'Ambient Generator', link: '/examples/ambient-generator' },
            { text: 'Visualization', link: '/examples/visualization' },
          ],
        },
      ],
      '/api/': typedocSidebar,
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/sethbrasile/ez-web-audio' },
    ],

    search: {
      provider: 'local',
    },
  },
})
