import { defineConfig } from 'vitepress'

// Import TypeDoc-generated sidebar (will exist after typedoc runs)
// Using dynamic import to avoid TS errors if file doesn't exist yet
let typedocSidebar: any[] = []
try {
  typedocSidebar = await import('../api/typedoc-sidebar.json')
  // Handle both default export and direct array
  if (typedocSidebar && 'default' in typedocSidebar) {
    typedocSidebar = (typedocSidebar as any).default
  }
} catch {
  // Will be generated by typedoc
}

export default defineConfig({
  title: 'EZ Web Audio',
  description: 'Making the Web Audio API super EZ since 2024',
  base: '/ez-web-audio/',

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Examples', link: '/examples/' },
      { text: 'API', link: '/api/' }
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
            { text: 'Core Concepts', link: '/guide/concepts' }
          ]
        }
      ],
      '/examples/': [
        {
          text: 'Examples',
          items: [
            { text: 'Overview', link: '/examples/' },
            { text: 'Basic Playback', link: '/examples/basic-playback' },
            { text: 'Synthesis', link: '/examples/synthesis' },
            { text: 'Effects', link: '/examples/effects' }
          ]
        }
      ],
      '/api/': typedocSidebar
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/sethbrasile/ez-web-audio' }
    ],

    search: {
      provider: 'local'
    }
  }
})
