import { defineConfig } from 'vitepress'

// Import TypeDoc-generated sidebar (will exist after typedoc runs)
// Using dynamic import to avoid TS errors if file doesn't exist yet
let typedocSidebar: any[] = []
try {
  typedocSidebar = await import('../api/typedoc-sidebar.json')
  // Handle both default export and direct array
  if (typedocSidebar && 'default' in typedocSidebar) {
    typedocSidebar = (typedocSidebar as any).default
  }
} catch {
  // Will be generated by typedoc
}

export default defineConfig({
  title: 'EZ Web Audio',
  description: 'Making the Web Audio API super EZ since 2024',
  base: '/ez-web-audio/',

  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Examples', link: '/examples/' },
      { text: 'API', link: '/api/' }
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
            { text: 'Core Concepts', link: '/guide/concepts' }
          ]
        }
      ],
      '/examples/': [
        {
          text: 'Examples',
          items: [
            { text: 'Overview', link: '/examples/' },
            { text: 'Basic Playback', link: '/examples/basic-playback' },
          ]
        },
        {
          text: 'Sampling',
          items: [
            { text: 'Sampled Drum Kit', link: '/examples/sampled-drum-kit' },
            { text: 'Soundfont Piano', link: '/examples/soundfont-piano' },
          ]
        },
        {
          text: 'Synthesis',
          items: [
            { text: 'Synthesis', link: '/examples/synthesis' },
            { text: 'Synth Keyboard', link: '/examples/synth-keyboard' },
            { text: 'XY Pad', link: '/examples/xy-pad' },
            { text: 'Synth Drum Kit', link: '/examples/synth-drum-kit' },
          ]
        },
        {
          text: 'Timing & Sequencing',
          items: [
            { text: 'Timing Basics', link: '/examples/timing' },
            { text: 'Drum Machine', link: '/examples/drum-machine' },
          ]
        },
        {
          text: 'Integration Patterns',
          items: [
            { text: 'Vue Reactive Pattern', link: '/examples/drum-machine-vue' },
            { text: 'Vanilla TS Events', link: '/examples/drum-machine-vanilla' },
          ]
        },
        {
          text: 'Effects & Routing',
          items: [
            { text: 'Effects', link: '/examples/effects' },
            { text: 'Audio Routing', link: '/examples/audio-routing' },
          ]
        },
        {
          text: 'Creative',
          items: [
            { text: 'Ambient Generator', link: '/examples/ambient-generator' },
            { text: 'Visualization', link: '/examples/visualization' },
          ]
        }
      ],
      '/api/': typedocSidebar
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/sethbrasile/ez-web-audio' }
    ],

    search: {
      provider: 'local'
    }
  }
})
